### ISSUE TITLE
Question: Does foxy_sync support FoxyCart 1.1?

### ISSUE THREAD

**Issue by wrburgess** [tablexi/foxy_sync#1]
@cstump I'm starting a project that needs rails/ruby integration with FoxyCart and this seems like a good option. Does the gem support FoxyCart 1.1?

**Comment by cstump** [comment]
Thanks for your interest in FoxySync! I have not tried the gem with FoxyCart 1.1, but I believe it will work fine out of the box. [The change log for the release](http://www.foxycart.com/blog/1.1#.UgpTbGTEmgM) suggests that the FoxySync's supported services (cart validation, SSO, etc.) are the same as 1.0. I say give it a whirl. If you find a bug let me know and I'll work on a fix ASAP.

**Comment by wrburgess** [comment]
Cool, I'll be working on it the next few days and will let you know if anything comes up. Thanks!

**Comment by phred** [comment]
Hey, FoxyCart guy here — just confirming what @cstump said: no major changes in those services between 1.0 and 1.1.  Good luck!
