### ISSUE TITLE
Single Sign On: Works with Devise?

### ISSUE THREAD

**Issue by wrburgess** [tablexi/foxy_sync#3]
Using Rails 3.2 and the latest Devise for authentication, I'm getting this error when using the sso_user() method

```
# calling 

sso_url(params, current_user)

# response

<NoMethodError: undefined method `password_salt' for #<User:0x007fe272c0b078>>
```

This occurs when the `FoxySync::Api::Customer` class accesses the user object passed in and attempts to call `user.password_salt`. 

Is FoxySync compatible with Devise or do I need to build a custom process to interface with it?

**Comment by cstump** [comment]
FoxySync is compatible with Devise. I use the two gems together just fine. However, how you use Devise can make a difference. 

What is the schema for your users table? I imagine some field on it is meant to store your password salt. If so you could alias the method that field is read with to #password_salt.

**Comment by wrburgess** [comment]
Devise 3.1.0 doesn't have a password_salt method or field _if you are using bcyrpt_. 

However, I think it works if you create a `password_salt` instance method that returns the `authenticatable_salt` value. Still testing to be sure.

**Comment by cstump** [comment]
That makes sense; is in line with what I was thinking. For now I'd try putting `alias_method :password_salt, :authenticatable_salt` in your User class. A new version of FoxySync should be released to address this scenario.

**Comment by rebelvc** [comment]
When using devise, what password authentication method should I set foxycart to?
